name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_dropzone: ^3.0.5
  animated_background: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.13
  dart_code_viewer2: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
        - asset: assets/fonts/arialbd.ttf
          style: italic
    - family: Chillax
      fonts:
        - asset: assets/fonts/Chillax-Bold.ttf
          weight: 700
